//! Export for lege-docwrite.
//!
//! Planned: PDF generated by Lege itself through `lege-pdf-write`, Markdown
//! that keeps semantic structure and drops page geometry, and later IDML
//! (not native `.indd`) for InDesign interchange.
//!
//! This crate is a scaffold; see the project ledger (`.akr/`) for scope.
